name: Test

on:
  push:{branches: [master]}
  
env:
    UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
    UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
    UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
    
jobs:
  build: Run tests
  uses: webbertakken/unity-test-runner@v1.6
  with:
    projectPath: ./
    unityVersion: 2019.3.2f1
