name: Test

on:
  push

jobs:
  test-job:
    name: Run tests
    runs-on: macOS-latest
    env:
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
    run: echo "Hello World"
    # uses: webbertakken/unity-test-runner@v1.6
    # with:
    #   projectPath: ./
    #   unityVersion: 2019.3.2f1

